version: 2

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  draft: true
  replace_existing_draft: true

archives:
  - format_overrides:
      - goos: windows
        format: zip

brews:
  - name: nctl

    # GOARM to specify which 32-bit arm version to use if there are multiple
    # versions from the build section. Brew formulas support only one 32-bit
    # version.
    # Default is 6 for all artifacts or each id if there are multiple versions.
    goarm: 6

    # GOAMD64 to specify which amd64 version to use if there are multiple
    # versions from the build section.
    # Default is v1.
    goamd64: v1

    repository:
      owner: ninech
      name: homebrew-taps
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    url_template: "https://github.com/ninech/nctl/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_author:
      name: nine.ch Bot
      email: ninech-bot@users.noreply.github.com

    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/ninech/nctl"
    description: "Interact with Nine API resources."
    license: "Apache 2.0"

    # Setting this will prevent goreleaser to actually try to commit the updated
    # formula - instead, the formula file will be stored on the dist folder only,
    # leaving the responsibility of publishing it to the user.
    # If set to auto, the release will not be uploaded to the homebrew tap
    # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
    # Default is false.
    skip_upload: false

# .goreleaser.yaml
aurs:
  - name: nctl-bin
    homepage: "https://github.com/ninech/nctl"
    description: "A CLI tool to interact with Nine API resources."
    maintainers:
      - "nine"
    contributors:
      - "nine"
    license: "Apache 2.0"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/nctl-bin.git"
    commit_author:
      name: nine.ch Bot
      email: ninech-bot@users.noreply.github.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    url_template: "https://github.com/ninech/nctl/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    package: |-
      install -Dm 0755 "${srcdir}"/nctl "${pkgdir}"/usr/bin/nctl
      install -Dm 0644 "${srcdir}"/LICENSE "${pkgdir}"/usr/share/licenses/$pkgname/LICENSE
      install -Dm 0644 "${srcdir}"/README.md "${pkgdir}"/usr/share/doc/$pkgname/README.md

nfpms:
  - id: packages
    license: Apache 2.0
    formats:
      - deb
      - rpm
    package_name: nctl
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    maintainer: 'Nine Platform Team <platform@nine.ch>'

publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/ninedev/

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
